### ISSUE TITLE
THREE is not defined on three-spritetext.module.js

### ISSUE THREAD

**Issue by pedrobernardina** [vasturiano/three-spritetext#2]
Installing your module with NPM gave me the error above.

I've managed to 'fix' it by putting this line on the top of the file:

var three = window.THREE ? window.THREE : require('three'); // Prefer consumption from global THREE, if exists

I'm just not sure if this is the right approach (also, this change will be lost on another machine)

**Comment by vasturiano** [comment]
@pedrobernardina thanks for reaching out. 
This error is expected, since `three` is a `peerDependency` of this module. The consumer needs to provide an instance of `three` for it to work. Possibly you've got a warning while NPM installing also mentioning this.

**Comment by KorbinianK** [comment]
Same problem here. Three is imported, defined and working. Yet this addon won't work, throwing the error above.

**Comment by vasturiano** [comment]
@KorbinianK @pedrobernardina there was an issue with the ES modules setup for three in the lib, that was causing it to only work in UMD mode, not when imported (or required).
That's now fixed in `v1.0.6`, so you shouldn't experience the issue any more if you upgrade.
Let me know if you run into any other problems, and thanks for reporting!
