### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'LinearFilter')

### ISSUE THREAD

**Issue by timonson** [vasturiano/three-spritetext#45]
Using your example in the doc, I get this error just importing the modules via unpkg.

> Uncaught TypeError: Cannot read properties of undefined (reading 'LinearFilter')

Can you help me with that? Thank you!

**Comment by lborgman** [comment]
I saw this problem first today. Just doing this:

    <script src="https://unpkg.com/three"></script>
    <script src="https://unpkg.com/three-spritetext"></script>

This worked yesterday and have done so for a long time.

The code that fails now is this in three-spritetext:

    var c = "undefined" != typeof window && window.THREE ? window.THREE : {
        LinearFilter: t.LinearFilter,

Sorry I do not have the line numbers. (They seem to disappear somewhere in the building process for three-spritetext.)

**Comment by lborgman** [comment]
As a workaround I use the previous version of three.js:

    <script src="https://unpkg.com/three@0.160.1"></script>
    
 (But three.js tells me, as it always has done, that I should use the ES module version instead. I have not had time to look into that yet.)

**Comment by raphaelsty** [comment]
Encountered the same problem, following @lborgman solution, fixing three.js version by replacing `<script src="https://unpkg.com/three"></script>` by `<script src="https://unpkg.com/three@0.160.1"></script>` solved the problem.

**Comment by timonson** [comment]
It is not doing this for me. I have this code:

```js
import "https://unpkg.com/3d-force-graph";
import "https://unpkg.com/three@0.160.1";
import { addNode, handleNodeClick } from "/content/section/dropdown.js";

const forceGraphContainer = document.querySelector("#force-graph-container");

const graph = ForceGraph3D();
graph(forceGraphContainer)
  .graphData(data)
  // .nodeLabel("id")
  .nodeAutoColorBy("group")
  .nodeThreeObject((node) => {
    const sprite = new SpriteText(node.id);
    sprite.material.depthWrite = false; // make sprite background transparent */
    sprite.color = node.color;
    sprite.textHeight = 8;
    return sprite;
  })
```
I get this error:

> force-graph.js:16 Uncaught ReferenceError: SpriteText is not defined
    at force-graph.js:16:20
    at createObj (3d-force-graph.min.js:5:25806)
    at 3d-force-graph.min.js:2:540102
    at Array.forEach (<anonymous>)
    at 3d-force-graph.min.js:2:540075
    at _u (3d-force-graph.min.js:2:540141)
    at Eh (3d-force-graph.min.js:5:10011)
    at Function.update (3d-force-graph.min.js:5:25606)
    at 3d-force-graph.min.js:2:530618
    at p (3d-force-graph.min.js:2:527363)

**Comment by vasturiano** [comment]
The root of the issue is that ThreeJS has dropped support for UMD targets in the latest release (161), that came out about 2 weeks ago.
You can read a bit more about it here: https://github.com/mrdoob/three.js/wiki/Migration-Guide#r160--r161

So, essentially one can't just do `<script src="//unpkg.com/three">` anymore.

To solve this there's two options, one can either pin down to version 160 (`//unpkg.com/three@0.160`) as was mentioned by @lborgman. Or update the html code to import three via ES modules. This is a bit of a longer route, but it's the best option to have it forward compatible. That's what I've done to the example on this package:
https://github.com/vasturiano/three-spritetext/blob/a05142e8b72bc687b6fabd197578f27c9023a814/example/basic/index.html#L14-L17
