### ISSUE TITLE
Flickering when zoomed out

### ISSUE THREAD

**Issue by lluis** [vasturiano/three-spritetext#48]
Hi, is there any way to prevent the flickering when moving camera while zoomed out? Specially for texts with stroke
See for example the demo page from https://vasturiano.github.io/three-spritetext/example/basic/

**Comment by vasturiano** [comment]
@lluis thanks for reaching out.

The reason for most of the flickering during the zooming operations was because the texture had a linear [minification filter](https://threejs.org/docs/#api/en/textures/Texture.minFilter). 
This makes the text a slightly more crisp but has the unwanted side effect of sub-pixel flickering when the camera moves.
I've changed the `minFilter` to the default [LinearMipmapLinearFilter](https://threejs.org/docs/index.html#api/en/constants/Textures) which I think it's more suiting to this text representation.

In any case any other filter can still be applied on demand by setting it on the text sprite, something like:
```js
myTextSprite.material.map.minFilter = THREE.NearestFilter;
```

**Comment by lluis** [comment]
@vasturiano Thanks for the fix! :smile:
